#!/bin/bash
set -e
cd "$( dirname "${BASH_SOURCE[0]}" )"
../get_dependencies.sh

set -x
rm -rf build/
autoreconf -if
mkdir -p build/
cd build/
../configure --enable-silent-rules
set +x

echo -e "\e[32mMakefile gerado em build/"
